modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/MC-U-Team/Extreme-Cobble-Generator/issues"
displayURL="https://u-team.info/mods/extremecobblegenerator"
logoFile="logo.png"
license="Apache-2.0 License"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="extremecobblegenerator"
	version="${file.jarVersion}"
	displayName="Extreme Cobble Generator"
	updateJSONURL="https://api.u-team.info/update/extremecobblegenerator.json"
	description="This mod adds an extreme cobblestone generator that generates cobblestone from FE."
	
	[[dependencies.extremecobblegenerator]]
	    modId="forge"
	    mandatory=true
	    versionRange="[36.1.30,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.extremecobblegenerator]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.16.5]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.extremecobblegenerator]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[3.2.1.229,)"
	    ordering="NONE"
	    side="BOTH"